[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
esscrow = "9xrCeAwu6tvm3fMXK1wxjgXFpnPF5ckA7gmoZFVWhZyo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/salman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
